version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
      # Use Indian Standard Time (UTC +05:30)
      timezone: "Asia/Kolkata"
      time: "09:00"
    # Raise pull requests for version updates
    # to pip against the `develop` branch
    target-branch: "develop"
