---
services:
  _defaults:
    autoconfigure: true
    autowire: true
    public: true

  AcquiaCMS\Cli\:
    exclude: ../src/Kernel.php
    public: false
    resource: ../src

  Symfony\Component\Console\Application:
    public: true
  AcquiaCMS\Cli\Commands\AcmsInstallCommand:
    arguments:
      $project_dir: "%kernel.project_dir%"
