name: acquia-cms-starterkit CI
on:
  schedule:
    # "At minute 0 past hour 4 and 8 UTC."
    - cron:  '0 4,8 * * *'
  push:
    branches: [ develop, main, ACMS* ]
    paths-ignore:
      - README.md
  pull_request:
    branches: [ develop ]
    paths-ignore:
      - README.md
jobs:
  # @todo add tests to validate each starter-kit use case.
  STATIC_CODE_ANALYSIS:
    name: "Static Code Analysis"
    runs-on: ubuntu-latest
    env:
      ORCA_SUT_NAME: acquia/acquia-cms-starterkit
      ORCA_JOB: STATIC_CODE_ANALYSIS
      ORCA_SUT_BRANCH: develop
      ORCA_VERSION: ^3
      ORCA_PACKAGES_CONFIG_ALTER: ../acquia-cms-starterkit/tests/packages_alter.yml
      ORCA_ENABLE_NIGHTWATCH: "FALSE"
      ORCA_PHPCS_STANDARD: AcquiaPHP
      COMPOSER_PROCESS_TIMEOUT: 1800
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          coverage: xdebug
      - name: Download ORCA
        run: composer create-project --no-dev --ignore-platform-req=php acquia/orca ../orca "$ORCA_VERSION" -n
      - name: Run GrumpPHP tests
        run: |
          composer install
          ./vendor/bin/grumphp run
      - name: Before Install
        run: ../orca/bin/ci/before_install.sh
      - name: Install
        run: ../orca/bin/ci/install.sh
      - name: Before script
        run: ../orca/bin/ci/before_script.sh
      - name: Script
        run: ../orca/bin/ci/script.sh
      - name: After script
        run: |
          ../orca/bin/ci/after_success.sh
          ../orca/bin/ci/after_failure.sh
          ../orca/bin/ci/after_script.sh
  VERIFY_ACMS_STARTERKIT_ON_DRUPAL_PROJECT:
    if: ${{ github.event_name == 'push' }}
    name: "Verify ${{ matrix.starter-kits }} with demo-content=${{ matrix.demo-content }}, content-model=${{ matrix.content-model }}, dam-integration=${{ matrix.dam-integration }}, core-version=${{ matrix.core-version }} on acquia/drupal-recommended-project"
    runs-on: ubuntu-latest
    env:
      ORCA_SUT_NAME: acquia/acquia-cms-starterkit
      ORCA_SUT_BRANCH: develop
      ORCA_VERSION: ^3
      ORCA_PACKAGES_CONFIG_ALTER: ../acquia-cms-starterkit/tests/packages_alter.yml
      ORCA_ENABLE_NIGHTWATCH: "FALSE"
      DB_DATABASE: drupal
      DB_USER: drupal
      DB_PASSWORD: drupal
      COMPOSER_PROCESS_TIMEOUT: 1800
      demo_content: ${{ matrix.demo-content }}
      content_model: ${{ matrix.content-model }}
      dam_integration: ${{ matrix.dam-integration }}
      # nextjs_app: ${{ matrix.nextjs-app }}
      CI: TRUE
    strategy:
      matrix:
        core-version: ["CURRENT"]
        starter-kits: ["acquia_cms_enterprise_low_code", "acquia_cms_community", "acquia_cms_headless"]
        demo-content: ["yes", "no"]
        content-model: ["yes", "no"]
        dam-integration: ["yes", "no"]
        # nextjs-app: ["yes", "no"]
        exclude:
          - demo-content: "yes"
            content-model: "yes"
          - demo-content: "no"
            content-model: "no"
            dam-integration: "yes"
          - demo-content: "yes"
            content-model: "no"
            dam-integration: "no"
          # - starter-kits: ["acquia_cms_enterprise_low_code", "acquia_cms_community"]
          #   nextjs-app: "yes"
          # - starter-kits: ["acquia_cms_headless"]
          #   demo-content: "no"
          #   content-model: "no"
          #   nextjs-app: "yes"
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          coverage: xdebug
      - name: Set up MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -uroot -proot
          mysql -e 'SHOW DATABASES;' -uroot -proot
          mysql -e 'CREATE USER "drupal"@"localhost" IDENTIFIED BY "drupal";' -uroot -proot
          mysql -e 'GRANT ALL PRIVILEGES ON *.* TO "drupal"@"localhost" WITH GRANT OPTION;' -uroot -proot
          mysql -e 'FLUSH PRIVILEGES;' -uroot -proot
          mysql -e 'SHOW GRANTS FOR "drupal"@"localhost";' -uroot -proot
      - name: Download Composer Dependencies
        run: composer install
      - name: Download ORCA
        run: |
          cd ..
          composer create-project --no-dev --ignore-platform-req=php acquia/orca orca "$ORCA_VERSION"
          cd -
      - name: Before Install
        run: ../orca/bin/orca fixture:init --project-template=acquia/drupal-recommended-project --core=${{ matrix.core-version }} --sut=$ORCA_SUT_NAME --no-site-install
      - name: Install
        run: |
          cd ../orca-build
          composer config -g github-oauth.github.com ${{ secrets.OAUTH_TOKEN }}
          ./vendor/bin/acms acms:install ${{ matrix.starter-kits }} --no-interaction
      - name: Execute all PHPUnit tests
        run: ./vendor/bin/phpunit
      - name: Before script
        run: ../orca/bin/ci/before_script.sh
      - name: Script
        run: ../orca/bin/ci/script.sh
      - name: After script
        run: |
          ../orca/bin/ci/after_success.sh
          ../orca/bin/ci/after_failure.sh
          ../orca/bin/ci/after_script.sh
  VERIFY_ACMS_INSTALL_CURRENT_PROJECT:
    name: "Verify commands on current project (Non Drupal)"
    runs-on: ubuntu-latest
    env:
      ORCA_SUT_NAME: acquia/acquia-cms-starterkit
      ORCA_SUT_BRANCH: develop
      ORCA_VERSION: ^3
      ORCA_PACKAGES_CONFIG_ALTER: ../acquia-cms-starterkit/tests/packages_alter.yml
      ORCA_ENABLE_NIGHTWATCH: "FALSE"
      DB_DATABASE: drupal
      DB_USER: drupal
      DB_PASSWORD: drupal
      COMPOSER_PROCESS_TIMEOUT: 1800
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          coverage: xdebug
      - name: Set up MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -uroot -proot
          mysql -e 'SHOW DATABASES;' -uroot -proot
          mysql -e 'CREATE USER "drupal"@"localhost" IDENTIFIED BY "drupal";' -uroot -proot
          mysql -e 'GRANT ALL PRIVILEGES ON *.* TO "drupal"@"localhost" WITH GRANT OPTION;' -uroot -proot
          mysql -e 'FLUSH PRIVILEGES;' -uroot -proot
          mysql -e 'SHOW GRANTS FOR "drupal"@"localhost";' -uroot -proot
      - name: Download Composer Dependencies
        run: composer install
      - name: Install
        run: ./bin/acms acms:install --no-interaction
      - name: Execute all PHPUnit tests
        run: ./vendor/bin/phpunit
